# name of your application
APPLICATION = shell_one

# If no BOARD is found in the environment, use this default:
BOARD ?= native

# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../..

USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += uart0

include $(RIOTBASE)/Makefile.include
